version: '3.8'
services:
  java-maven-app:
    image: ${IMAGE} #"knbd2015/demo-app:${TAG}" #knbd2015/demo-app:java-maven-1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=my-pwd
